--
--   Copyright 2012 Norio Agawa
--
--   Licensed under the Apache License, Version 2.0 (the "License");
--   you may not use this file except in compliance with the License.
--   You may obtain a copy of the License at
--
--       http://www.apache.org/licenses/LICENSE-2.0
--
--   Unless required by applicable law or agreed to in writing, software
--   distributed under the License is distributed on an "AS IS" BASIS,
--   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
--   See the License for the specific language governing permissions and
--   limitations under the License.
--

-- スキーマ作成
-- DROP TABLE member;
CREATE TABLE member (
	id		BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 10, INCREMENT BY 1),
	login	VARCHAR(32) NOT NULL,
	passwd	VARCHAR(64) NOT NULL,
	name	VARCHAR(255),
	memo	VARCHAR(1024),
	del_flg	CHAR(1)	DEFAULT '0'
);
ALTER TABLE member ADD PRIMARY KEY (id);

-- 初期データ投入
INSERT INTO member (login, passwd) VALUES ('user0', 'user0');
INSERT INTO member (login, passwd) VALUES ('user1', 'user1');
INSERT INTO member (login, passwd) VALUES ('user2', 'user2');
INSERT INTO member (login, passwd) VALUES ('user3', 'user3');
INSERT INTO member (login, passwd) VALUES ('user4', 'user4');
INSERT INTO member (login, passwd) VALUES ('user5', 'user5');
INSERT INTO member (login, passwd) VALUES ('user6', 'user6');
INSERT INTO member (login, passwd) VALUES ('user7', 'user7');
INSERT INTO member (login, passwd) VALUES ('user8', 'user8');
INSERT INTO member (login, passwd) VALUES ('user9', 'user9');

-- データ更新
UPDATE member SET name = login, del_flg = '0';
